{
 "title": "CEF Sandbox Usage - II",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Active Instances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "resource_id" ], "type": "tag" }
     ],
     "measurement": "instance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "Vicenza" },
      {
       "condition": "AND",
       "key": "user_id",
       "operator": "=",
       "value": "86b687f4f3704dda91f21ba5d1375940"
      }
     ]
    }
   ]
  },
  {
   "title": "Accumulative Network Incoming",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network.incoming.bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "Vicenza" },
      {
       "condition": "AND",
       "key": "user_id",
       "operator": "=",
       "value": "86b687f4f3704dda91f21ba5d1375940"
      }
     ]
    }
   ]
  },
  {
   "title": "Accumulative Network Outgoing",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network.outgoing.bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "Vicenza" },
      {
       "condition": "AND",
       "key": "user_id",
       "operator": "=",
       "value": "86b687f4f3704dda91f21ba5d1375940"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Outgoing Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "resource_id" ], "type": "tag" }
     ],
     "measurement": "network.outgoing.bytes.rate",
     "query": "SELECT \"value\" FROM \"network.outgoing.bytes.rate\" WHERE (\"region\" = 'Vicenza' AND \"user_id\" = '86b687f4f3704dda91f21ba5d1375940') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "Vicenza" },
      {
       "condition": "AND",
       "key": "user_id",
       "operator": "=",
       "value": "86b687f4f3704dda91f21ba5d1375940"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Incoming Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "resource_id" ], "type": "tag" }
     ],
     "measurement": "network.incoming.bytes.rate",
     "query": "SELECT \"value\" FROM \"network.outgoing.bytes.rate\" WHERE (\"region\" = 'Vicenza' AND \"user_id\" = '86b687f4f3704dda91f21ba5d1375940') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "Vicenza" },
      {
       "condition": "AND",
       "key": "user_id",
       "operator": "=",
       "value": "86b687f4f3704dda91f21ba5d1375940"
      }
     ]
    }
   ]
  }
 ]
}