{
 "title": "CEF Sandbox usage - I",
 "time": { "from": "2019-03-08T11:21:40.135Z", "to": "2019-03-11T21:50:19.030Z" },
 "panels": [
  {
   "title": "Memory Usage [%]",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "resource_id" ], "type": "tag" }
     ],
     "measurement": "memory_util",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "Vicenza" },
      {
       "condition": "AND",
       "key": "user_id",
       "operator": "=",
       "value": "86b687f4f3704dda91f21ba5d1375940"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "memory.usage",
     "query": "SELECT sum(\"value\") FROM \"memory.usage\" WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "Vicenza" }
     ]
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "resource_id" ], "type": "tag" }
     ],
     "measurement": "disk.write.bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "Vicenza" },
      {
       "condition": "AND",
       "key": "user_id",
       "operator": "=",
       "value": "86b687f4f3704dda91f21ba5d1375940"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "resource_id" ], "type": "tag" }
     ],
     "measurement": "disk.read.bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "Vicenza" },
      {
       "condition": "AND",
       "key": "user_id",
       "operator": "=",
       "value": "86b687f4f3704dda91f21ba5d1375940"
      }
     ]
    }
   ]
  },
  {
   "title": "Total CPU Usage [%]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "measurement": "cpu_util",
     "query": "SELECT \"value\" FROM \"cpu_util\" WHERE (\"region\" = 'Vicenza' AND \"user_id\" = '86b687f4f3704dda91f21ba5d1375940') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "Vicenza" },
      {
       "condition": "AND",
       "key": "user_id",
       "operator": "=",
       "value": "86b687f4f3704dda91f21ba5d1375940"
      }
     ]
    }
   ]
  },
  {
   "title": "Accumulative vCPUs consumed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "vcpus",
     "query": "SELECT sum(\"value\") FROM \"vcpus\" WHERE (\"region\" = 'Vicenza' AND \"user_id\" = '86b687f4f3704dda91f21ba5d1375940') AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "Vicenza" },
      {
       "condition": "AND",
       "key": "user_id",
       "operator": "=",
       "value": "86b687f4f3704dda91f21ba5d1375940"
      }
     ]
    }
   ]
  }
 ]
}