version: '3'

volumes:
    grafana_data: {}

services:
   grafana:
        image: grafana/grafana
        user: "104"
        ports:
          - 3001:3000
        volumes:
          - grafana_data:/var/lib/grafana
          - ./configs/${SERVICE}/provisioning/:/etc/grafana/provisioning/
        env_file:
          - ./configs/config.grafana
        restart: always
