{
 "title": "FIWARE GE SLA",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "GE",
    "label": "FIWARE GE",
    "query": "Cygnus, QuantumLeap, Orion, Orion-LD, STH-Comet, FastRTPS, Micro XRCE-DDS, Draco, IDAS, Wirecloud, Knowage, OpenMTC, Domibus, FogFlow, Perseo, Kurento, Cosmos, AuthZForce, CKAN Extensions, KeyRock, Wilma, APInf, BIZ Framework, Idra,"
   }
  ]
 },
 "panels": [
  {
   "title": "$GE: Number of tickets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.tickets_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=~", "value": "/^$GE$/" }
     ]
    }
   ]
  },
  {
   "title": "$GE: Response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "d" }
   ],
   "targets": [
    {
     "measurement": "ge.ticket_response_time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=~", "value": "/^$GE$/" }
     ]
    }
   ]
  },
  {
   "title": "$GE: Resolve time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "d" }
   ],
   "targets": [
    {
     "measurement": "ge.ticket_resolve_time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=~", "value": "/^$GE$/" }
     ]
    }
   ]
  }
 ]
}