{
 "title": "FIWARE GEs metrics dashboard",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "GE",
    "label": "Generic Enabler",
    "query": "Orion - Context Broker, Orion-LD"
   }
  ]
 },
 "panels": [
  {
   "title": "$GE: Catalogue Page Views",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.pageviews.catalogue",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=~", "value": "/^$GE$/" }
     ]
    }
   ]
  },
  {
   "title": "$GE: Academy Page Views",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.pageviews.academy",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=~", "value": "/^$GE$/" }
     ]
    }
   ]
  },
  {
   "title": "$GE: ReadTheDocs Page Views",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.pageviews.rtd",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=~", "value": "/^$GE$/" }
     ]
    }
   ]
  },
  {
   "title": "$GE: Docker Pulls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.docker.pulls",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=~", "value": "/^$GE$/" }
     ]
    }
   ]
  },
  {
   "title": "$GE: GitHub Total Assets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.gh.assets.total",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=~", "value": "/^$GE$/" }
     ]
    }
   ]
  },
  {
   "title": "$GE: GitHub Download Assets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.gh.assets.downloads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=~", "value": "/^$GE$/" }
     ]
    }
   ]
  },
  {
   "title": "$GE: GitHub Open Issues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.gh.issues.open",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=~", "value": "/^$GE$/" }
     ]
    }
   ]
  },
  {
   "title": "$GE: GitHub Closed Issues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.gh.issues.closed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=~", "value": "/^$GE$/" }
     ]
    }
   ]
  },
  {
   "title": "$GE: GitHub Total Adopters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.gh.adopters.total",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=~", "value": "/^$GE$/" }
     ]
    }
   ]
  },
  {
   "title": "$GE: GitHub Open Issues from Adopters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.gh.adopters.issues.open",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=~", "value": "/^$GE$/" }
     ]
    }
   ]
  },
  {
   "title": "$GE: GitHub Closed Issues from Adopters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.gh.adopters.issues.closed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=~", "value": "/^$GE$/" }
     ]
    }
   ]
  },
  {
   "title": "$GE: GitHub Commits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.gh.commits",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=~", "value": "/^$GE$/" }
     ]
    }
   ]
  },
  {
   "title": "$GE: Coveralls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.coveralls",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=~", "value": "/^$GE$/" }
     ]
    }
   ]
  },
  {
   "title": "$GE: Help-Desk tickets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.helpdesk.tickets",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=~", "value": "/^$GE$/" }
     ]
    }
   ]
  },
  {
   "title": "$GE: Help-Desk Pending Tickets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "measurement": "ge.helpdesk.pending",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=~", "value": "/^$GE$/" }
     ]
    }
   ]
  },
  {
   "title": "$GE: Help-Desk Mean Pending Tickets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 24 },
   "yaxes": [
    { "format": "d" }
   ],
   "targets": [
    {
     "measurement": "ge.helpdesk.days",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=~", "value": "/^$GE$/" }
     ]
    }
   ]
  },
  {
   "title": "$GE: GitHub Forks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.gh.forks",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=~", "value": "/^$GE$/" }
     ]
    }
   ]
  },
  {
   "title": "$GE: GitHub Watchers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.gh.watchers",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=~", "value": "/^$GE$/" }
     ]
    }
   ]
  },
  {
   "title": "$GE: GitHub Stars",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.gh.stars",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=~", "value": "/^$GE$/" }
     ]
    }
   ]
  }
 ]
}