# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: InfluxDB
    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
  # <string, required> name of the datasource. Required
  - name: InfluxDB
    # <string, required> datasource type. Required
    type: influxdb
    # <string, required> access mode. direct or proxy. Required
    access: proxy
    # <int> org id. will default to orgId 1 if not specified
    orgId: 1
    # <string> url
    url: a-specific-url
    # <string> database user, if used
    user: a-user
    # <string> database name, if used
    database: a-db
    # <bool> enable/disable with credentials headers
    withCredentials: false
    # <bool> mark as default datasource. Max one per org
    isDefault: true
    version: 1
    # <bool> allow users to edit datasources from the UI.
    editable: false
    # <string> json object of data that will be encrypted.
    secureJsonData:
      # <string> database password, if used
      password: other-super-secret
